# Admin
holter_admin:
    defaults: { _controller:  JiabinHolterBundle:Admin:index }
    pattern:  /admin

holter_admin_new_check:
    defaults: { _controller:  JiabinHolterBundle:Admin:newCheck }
    pattern:  /admin/check/new

holter_admin_edit_check:
    defaults: { _controller:  JiabinHolterBundle:Admin:editCheck }
    pattern:  /admin/check/{id}/edit

holter_admin_delete_check:
    defaults: { _controller:  JiabinHolterBundle:Admin:deleteCheck }
    pattern:  /admin/check/{id}/delete
    methods:  [GET, POST]

holter_admin_config:
    defaults: { _controller:  JiabinHolterBundle:Admin:indexConfig }
    pattern:  /admin/config
    methods:  [GET, POST]
