# Holter
holter:
    defaults:  { _controller:  JiabinHolterBundle:Default:index }
    pattern: /

# Api
holter_api:
    resource: "@JiabinHolterBundle/Resources/config/routing/api.yml"
    prefix:   /